### ISSUE TITLE
Csv file considers different columns as one

### ISSUE THREAD

**Issue by pranjal-git** [yiannakasgeorge/TwittyJar#5]
While the csv file is getting exported correctly the file on opening in  excel considers only that the file has one column and  there is no clear demarcation between the column fields. This  is after setting the delimiter options and other settings correctly.

**Comment by pranjal-git** [comment]
only download the file located in dist folder

**Comment by yiannakasgeorge** [comment]
Hey! Thanks for your comments. I have created an instructional video on how to convert the CSV to an excel spreadsheet in seconds : https://www.youtube.com/watch?v=4a3I5oLj3JU
