### ISSUE TITLE
The app cannot retrieve full twitt when there is a comma ( , )

### ISSUE THREAD

**Issue by jamal14177** [yiannakasgeorge/TwittyJar#6]
**Describe the bug** - The app cannot retrieve full twitt when there is a comma ( , ) in the sentence. It only capture words before the comma and it ignore those words after the comma

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Google chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] laptop

**Additional context**

**Comment by yiannakasgeorge** [comment]
Thank you Jamal and apologies for the late reply. Will look into it!

**Comment by jamal14177** [comment]
Hi Yiannakasgeorge/Twittyjar

I think the problem is when i used the method that you showed on how to
transfer the data to excel. I think it will discard everything after the
comma. When i retrived the data from TwitterJar, it gave me full tweets. It
just that when I format it in excell. That is why i kept it as it is,
without reformat in the excell. Anyway, i want to thank you for this
excellence app, im currently using it in my research. Thank you again.
